// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgfixrbwptoefiyofixe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnZml4cmJ3cHRvZWZpeW9maXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1NDMwMTcsImV4cCI6MjA4MDExOTAxN30.8NLcNeXQx10LZq6e4iRdh_FvFZRCITZ6e3SsGFGP1Ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});