// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlhsyqieferpzvlfoudn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsaHN5cWllZmVycHp2bGZvdWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5Nzc2NjMsImV4cCI6MjA3NTU1MzY2M30.TTweMI03hdnLVLrl3qJmanrcYqHLuVtleoK_cCLgJt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});